_parent_: configs/reconstruct/base.yaml


data:
  case: big_wavy1
  image_size: [1920,1080]
  frame_interval: 7

prepare_data:
    fit_bust:

ngp:
  marching_cubes_density_thresh: 3.0


PMVO:
  num_sample_per_grid: 4
  patch_size: 7
  threshold: 0.025
  conf_threshold: 0.15



HairGenerate:
  connect_threshold: 0.0025
  grow_threshold: 0.85
  connect_dot_threshold: 0.8
  out_ratio: 0.35



