_parent_: configs/reconstruct/base.yaml


data:
  case: jenya2
  image_size: [1920,1080]
  frame_interval: 2
  conf_threshold: 0.4


PMVO:
   patch_size: 5
   conf_threshold: 0.1

ngp:
  marching_cubes_density_thresh: 2.5


HairGenerate:
  connect_threshold: 0.005
  grow_threshold: 0.9
  connect_dot_threshold: 0.85
  out_ratio: 0.



