_parent_: configs/reconstruct/base.yaml


data:
  case: white_curly1
  image_size: [1080,1920]
  frame_interval: 5

prepare_data:
  fit_bust:

ngp:
  marching_cubes_density_thresh: 3.2


LPMVS:
  num_sample_per_grid: 6
  patch_size: 5
  threshold: 0.02
  conf_threshold: 0.1

HairGenerate:
  connect_threshold: 0.005
  grow_threshold: 0.85
  connect_dot_threshold: 0.75
  dist_to_root: 15
  out_ratio: 0.