_parent_: configs/Bust_fit/base.yaml

subject: ksyusha1


savepath: data
subject_path: data/ksyusha1
camera_path: data/ksyusha1/ours/cam_params.json

data:
    image_size: [1920,1080]

smplx:
    n_shape: 300
    n_exp: 100



